### ISSUE TITLE
脚本不起作用

### ISSUE THREAD

**Issue by asterriya** [kkkyg/WarpEUserv#1]
我已经支持了指南上描述的系统，但它根本无法工作。

curl 已安装，继续 
wget 已安装，继续 
 VPS相关信息如下：
------------------------------------------
 操作系统名称 - Ubuntu 20.04 LTS 
 系统内核版本 - 5.4.0 
 CPU架构名称  - x86_64 
 虚拟架构类型 - kvm 
 -----------------------------------------------
ping: ipv4.google.com: Temporary failure in name resolution
ping: ipv6.google.com: Temporary failure in name resolution
 虚拟架构类型 -  kvm 
 对此vps架构不支持，脚本安装自动退出，赶紧提醒甬哥加上你的架构吧！

**Comment by kkkyg** [comment]
support ipv6 only vps
